apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kube-proj-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kube-proj-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
