apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-proj-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-proj
  template:
    metadata:
      labels:
        app: kube-proj
    spec:
      containers:
      - name: kube-proj-container
        image: kube-proj:1.0
        ports:
        - containerPort: 5000
