apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-proj-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kube-proj
  template:
    metadata:
      labels:
        app: kube-proj
    spec:
      containers:
      - name: kube-proj-container
        image: kube-proj:2.0
        ports:
        - containerPort: 5000
